
version: '3.8'
services:
  jenkins:
    build:
      context: .
    container_name: jenkins
    restart: unless-stopped
    privileged: true
    user: root
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_OPTS=--prefix=/jenkins
      - JENKINS_USER=admin
      - JENKINS_PASS=root
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/bin/docker-compose:/usr/bin/docker-compose
    ports:
      - 8080:8080
      - 50000:50000
volumes:
  jenkins_data:
    driver: local
    name: jenkins_data 